
name: MLOps Pipeline - Tourism Package Prediction

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:   # allows manual trigger

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r deployment/requirements.txt

    # Step 4: Run training
    - name: Run training pipeline
      run: |
        python training/train.py

    # Step 5: Run evaluation
    - name: Run evaluation
      run: |
        python training/evaluate.py

    # Step 6: Save trained model as artifact
    - name: Upload model artifact
      uses: actions/upload-artifact@v3
      with:
        name: model-artifact
        path: models/

  deploy-to-hf:
    needs: build-and-train
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install Hugging Face Hub
    - name: Install Hugging Face Hub
      run: pip install huggingface_hub

    # Step 4: Push deployment files to HF Space
    - name: Deploy to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        python deployment/push_to_hf.py
